### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Certseeds** [Fros1er/SUSTechCS208Labs#1]
hey,要不要考虑下用 [CS203-DSAA-Template](https://github.com/Certseeds/CS203_DSAA_template)当模板
+ 上交题目无需修改类名,方法名等等内容,只需复制粘贴.
+ 支持为每个问题撰写测试用例,并支持用户之间方便的交换测试用例
+ 只依赖于Unix-Like系统,支持C++17的编译器与仓库本身,没有依赖包
+ 易于拓展, 提供基本算法接口与实现

**Comment by Fros1er** [comment]
我下次写lab题的时候试试(
thx

**Comment by Fros1er** [comment]
还是决定摸了((
我个人写算法题还是喜欢搞得简单一些，需要测试的话也可以找神仙带带...
~~然后主要还是懒，dbq(...)~~
